-- Seed data for the IT03 approval exercise.
-- Regenerate by deleting db/app.db and starting the API once.

-- document_status
INSERT INTO "document_status" ("status_id", "status_code", "status_name_tha", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (1, 'PENDING', 'รออนุมัติ', 'SYSTEM', '2026-08-01 09:00:00', 'SEED', 'SYSTEM', '2026-08-01 09:00:00', 'SEED');
INSERT INTO "document_status" ("status_id", "status_code", "status_name_tha", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (2, 'APPROVED', 'อนุมัติ', 'SYSTEM', '2026-08-01 09:00:00', 'SEED', 'SYSTEM', '2026-08-01 09:00:00', 'SEED');
INSERT INTO "document_status" ("status_id", "status_code", "status_name_tha", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (3, 'REJECTED', 'ไม่อนุมัติ', 'SYSTEM', '2026-08-01 09:00:00', 'SEED', 'SYSTEM', '2026-08-01 09:00:00', 'SEED');

-- documents
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (1, 'รายการที่ 1', 'ขออนุมัติจัดซื้อวัสดุสำนักงาน ประจำเดือนสิงหาคม', 1, 'SYSTEM', '2026-08-01 09:00:00', 'SEED', 'SYSTEM', '2026-08-01 09:00:00', 'SEED');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (2, 'รายการที่ 2', 'ตรวจสอบเอกสารครบถ้วน อนุมัติตามระเบียบ', 2, 'SYSTEM', '2026-08-02 09:00:00', 'SEED', 'somchai.k', '2026-08-03 09:00:00', 'IT03');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (3, 'รายการที่ 3', 'เอกสารแนบไม่ครบ ขาดใบเสนอราคา', 3, 'SYSTEM', '2026-08-03 09:00:00', 'SEED', 'somchai.k', '2026-08-04 09:00:00', 'IT03');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (4, 'รายการที่ 4', 'ขออนุมัติเบิกค่าเดินทางไปราชการ', 1, 'SYSTEM', '2026-08-04 09:00:00', 'SEED', 'SYSTEM', '2026-08-04 09:00:00', 'SEED');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (5, 'รายการที่ 5', 'อยู่ในกรอบงบประมาณที่ได้รับจัดสรร', 2, 'SYSTEM', '2026-08-05 09:00:00', 'SEED', 'wanida.p', '2026-08-06 09:00:00', 'IT03');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (6, 'รายการที่ 6', 'เกินวงเงินที่หน่วยงานกำหนด', 3, 'SYSTEM', '2026-08-06 09:00:00', 'SEED', 'wanida.p', '2026-08-07 09:00:00', 'IT03');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (7, 'รายการที่ 7', 'ขออนุมัติจัดจ้างซ่อมบำรุงเครื่องปรับอากาศ', 1, 'SYSTEM', '2026-08-07 09:00:00', 'SEED', 'SYSTEM', '2026-08-07 09:00:00', 'SEED');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (8, 'รายการที่ 8', 'ขออนุมัติจัดอบรมบุคลากรภายใน', 1, 'SYSTEM', '2026-08-08 09:00:00', 'SEED', 'SYSTEM', '2026-08-08 09:00:00', 'SEED');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (9, 'รายการที่ 9', 'ขออนุมัติต่อสัญญาบริการระบบสารสนเทศ', 1, 'SYSTEM', '2026-08-09 09:00:00', 'SEED', 'SYSTEM', '2026-08-09 09:00:00', 'SEED');
INSERT INTO "documents" ("document_id", "document_name", "reason", "status_id", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (10, 'รายการที่ 10', 'ขออนุมัติจัดซื้อครุภัณฑ์คอมพิวเตอร์', 1, 'SYSTEM', '2026-08-10 09:00:00', 'SEED', 'SYSTEM', '2026-08-10 09:00:00', 'SEED');

-- approval_log
INSERT INTO "approval_log" ("approval_log_id", "document_id", "from_status_id", "to_status_id", "reason", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (1, 2, 1, 2, 'ตรวจสอบเอกสารครบถ้วน อนุมัติตามระเบียบ', 'somchai.k', '2026-08-03 09:00:00', 'IT03', 'somchai.k', '2026-08-03 09:00:00', 'IT03');
INSERT INTO "approval_log" ("approval_log_id", "document_id", "from_status_id", "to_status_id", "reason", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (2, 3, 1, 3, 'เอกสารแนบไม่ครบ ขาดใบเสนอราคา', 'somchai.k', '2026-08-04 09:00:00', 'IT03', 'somchai.k', '2026-08-04 09:00:00', 'IT03');
INSERT INTO "approval_log" ("approval_log_id", "document_id", "from_status_id", "to_status_id", "reason", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (3, 5, 1, 2, 'อยู่ในกรอบงบประมาณที่ได้รับจัดสรร', 'wanida.p', '2026-08-06 09:00:00', 'IT03', 'wanida.p', '2026-08-06 09:00:00', 'IT03');
INSERT INTO "approval_log" ("approval_log_id", "document_id", "from_status_id", "to_status_id", "reason", "created_by", "created_date", "created_program", "updated_by", "updated_date", "updated_program") VALUES (4, 6, 1, 3, 'เกินวงเงินที่หน่วยงานกำหนด', 'wanida.p', '2026-08-07 09:00:00', 'IT03', 'wanida.p', '2026-08-07 09:00:00', 'IT03');
